# Generated by Django 5.2.12 on 2026-03-31 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('video_games', 'Video Games'), ('trading_cards', 'Trading Cards'), ('comics', 'Comics'), ('funko_pops', 'Funko Pops'), ('lego_sets', 'LEGO Sets'), ('sports_cards', 'Sports Cards'), ('music', 'Music'), ('movies', 'Movies')], default='video_games', max_length=50),
        ),
        migrations.CreateModel(
            name='ComicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('issue_title', models.CharField(blank=True, default='', max_length=255)),
                ('issue_number', models.CharField(blank=True, default='', max_length=20)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('read_status', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comic', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='FunkoPopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, default='', max_length=255)),
                ('box_number', models.CharField(blank=True, default='', max_length=50)),
                ('completeness', models.CharField(blank=True, default='', max_length=100)),
                ('exclusive', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funko_pop', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='LegoSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, default='', max_length=255)),
                ('set_number', models.CharField(blank=True, default='', max_length=50)),
                ('completeness', models.CharField(blank=True, default='', max_length=100)),
                ('piece_count', models.IntegerField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lego_set', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='MovieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('format', models.CharField(blank=True, default='', max_length=50)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('watched_status', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='MusicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('album_title', models.CharField(blank=True, default='', max_length=255)),
                ('format', models.CharField(blank=True, default='', max_length=50)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='SportsCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, default='', max_length=100)),
                ('player_name', models.CharField(blank=True, default='', max_length=255)),
                ('card_number', models.CharField(blank=True, default='', max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sports_card', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='TradingCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, default='', max_length=255)),
                ('set_name', models.CharField(blank=True, default='', max_length=255)),
                ('card_number', models.CharField(blank=True, default='', max_length=50)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_card', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('completeness', models.CharField(blank=True, default='', max_length=100)),
                ('play_status', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_game', to='catalog.item')),
            ],
        ),
    ]
