# Generated by Django 5.2.14 on 2026-05-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_snapshots', to='catalog.collection')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('collection', 'date')},
            },
        ),
    ]
