# Generated by Django 6.0.3 on 2026-05-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_collection_type_comicitem_funkopopitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('owned', 'Owned'), ('wishlist', 'Wishlist')], default='owned', max_length=20),
        ),
    ]
