# Generated by Django 6.0.3 on 2026-05-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
