# Generated by Django 5.2.14 on 2026-05-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_wishlistitem'),
        ('catalog', '0004_alter_item_collection'),
    ]

    operations = [
    ]
