# Generated by Django 5.2.14 on 2026-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_item_status_user_clerk_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={},
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='collection_type',
            field=models.CharField(max_length=255),
        ),
    ]
