services:
  # The Backend playhouse
  backend:
    build: ./backend
    ports:
      - "9001:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1

  # The Frontend playhouse
  frontend:
    build: ./hoardhero-frontend
    ports:
      - "9000:5173"
    volumes:
      - ./hoardhero-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
